# Generated by Django 5.2.7 on 2025-12-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Design', 'Design'), ('Production', 'Production'), ('Quality', 'Quality'), ('Admin', 'Admin'), ('Logistics', 'Logistics')], max_length=50),
        ),
    ]
