# Generated by Django 5.2.7 on 2025-10-27 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique company code (e.g. SUP-001)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Only uppercase, numbers and hyphen')])),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique item code (e.g. ITM-001)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Only uppercase, numbers and hyphen')])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uom', models.CharField(default='NOS', max_length=20, verbose_name='Unit of Measure')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['code'],
            },
        ),
    ]
