# Generated by Django 5.2.7 on 2026-01-31 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique company code (e.g. SUP-001)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z\\-]+$', 'Only uppercase and hyphen')])),
                ('code2', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numbers allowed')], verbose_name='Numeric Code')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only digits allowed')])),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name as per Excel (e.g. COMPLETED, PENDING)', max_length=100, unique=True)),
                ('color_code', models.CharField(default='#6c757d', help_text='HEX color code (e.g. #28a745)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Status',
                'verbose_name_plural': 'Process Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentProcessMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Marketing', 'Marketing'), ('Design', 'Design'), ('Production', 'Production'), ('Quality', 'Quality'), ('Logistics', 'Logistics')], help_text='Owning department (cannot be changed later)', max_length=50)),
                ('name', models.CharField(help_text='Process name as per Excel', max_length=200)),
                ('sequence', models.PositiveIntegerField(help_text='Global execution order (1, 2, 3...)', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Disable instead of deleting or changing department')),
            ],
            options={
                'verbose_name': 'Department Process',
                'verbose_name_plural': 'Department Processes',
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['sequence'], name='master_depa_sequenc_250bb1_idx')],
            },
        ),
    ]
