# Generated by Django 5.2.7 on 2026-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprocessmaster',
            name='excludes_from_completion',
            field=models.BooleanField(default=False, help_text='If True, this process is excluded from PO completion check'),
        ),
        migrations.AddField(
            model_name='departmentprocessmaster',
            name='has_item_tracking',
            field=models.BooleanField(default=False, help_text='If True, user can set status per PO item during process update'),
        ),
        migrations.AddField(
            model_name='processstatusmaster',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='If True, this status counts as process completed'),
        ),
    ]
