# Generated by Django 5.2.7 on 2025-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='code2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Numaric Code'),
        ),
    ]
