# Generated by Django 5.2.7 on 2026-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_departmentprocessmaster_excludes_from_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
