# Generated by Django 5.2.7 on 2025-12-10 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_companymaster_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='code',
            field=models.CharField(help_text='Unique company code (e.g. SUP-001)', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z\\-]+$', 'Only uppercase and hyphen')]),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='code2',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9\\-]+$', 'Only numbers and hyphen')], verbose_name='Numaric Code'),
        ),
    ]
