# Generated by Django 5.2.7 on 2025-12-10 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_companymaster_code_alter_companymaster_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='code2',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only numbers allowed')], verbose_name='Numeric Code'),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Only digits allowed')]),
        ),
    ]
