# Generated by Django 5.2.7 on 2026-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_companymaster_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentprocessmaster',
            name='code',
            field=models.CharField(blank=True, help_text='Short code used for indent numbering (e.g. RAW, ACC, PAC). Only required for Production processes.', max_length=10),
        ),
    ]
