# Generated by Django 5.2.7 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_companymaster_code2_alter_companymaster_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Status name as per Excel (e.g. COMPLETED, PENDING)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Status',
                'verbose_name_plural': 'Process Statuses',
                'ordering': ['name'],
            },
        ),
    ]
