# Generated by Django 5.2.7 on 2025-12-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_processstatusmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProcessMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Marketing', 'Marketing'), ('Design', 'Design'), ('Production', 'Production'), ('Quality', 'Quality'), ('Logistics', 'Logistics')], help_text='Owning department (cannot be changed later)', max_length=50)),
                ('name', models.CharField(help_text='Process name as per Excel', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Disable instead of deleting or changing department')),
            ],
            options={
                'verbose_name': 'Department Process',
                'verbose_name_plural': 'Department Processes',
                'ordering': ['department', 'name'],
                'indexes': [models.Index(fields=['department'], name='master_depa_departm_df91d0_idx')],
                'unique_together': {('department', 'name')},
            },
        ),
    ]
