# Generated by Django 5.2.7 on 2025-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_departmentprocessmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstatusmaster',
            name='color_code',
            field=models.CharField(default='#6c757d', help_text='HEX color code (e.g. #28a745)', max_length=7),
        ),
    ]
