# Generated by Django 5.2.7 on 2026-01-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_processstatusmaster_color_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemMaster',
        ),
    ]
