# Generated by Django 5.2.7 on 2026-01-31 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_number', models.CharField(blank=True, editable=False, help_text='System generated indent number', max_length=50, unique=True)),
                ('indent_date', models.DateField(help_text='Date when indent is raised')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_indents', to=settings.AUTH_USER_MODEL)),
                ('po_process', models.ForeignKey(help_text='Production process during which indent is raised', on_delete=django.db.models.deletion.PROTECT, related_name='indents', to='po.poprocess')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indents', to='po.purchaseorder')),
            ],
            options={
                'verbose_name': 'Indent',
                'verbose_name_plural': 'Indents',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, help_text='Quantity required for this PO item', max_digits=12)),
                ('uom', models.CharField(help_text='Unit of Measure (default from PO item)', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='indent.indent')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indent_items', to='po.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Indent Item',
                'verbose_name_plural': 'Indent Items',
                'ordering': ['id'],
            },
        ),
    ]
