# Generated by Django 5.2.7 on 2026-03-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_remove_bomitem_unique_po_item_per_bom_and_more'),
        ('indent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indent',
            name='status',
        ),
        migrations.AlterField(
            model_name='indent',
            name='indent_number',
            field=models.CharField(blank=True, editable=False, help_text='System generated: IND/{oa_number}/{CODE}/{0001}', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='indentitem',
            name='uom',
            field=models.CharField(help_text='Unit of Measure (carried from PO item)', max_length=20),
        ),
        migrations.CreateModel(
            name='IndentSubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Material / component name', max_length=255)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('bom_item', models.ForeignKey(blank=True, help_text='Set when sub-item was pulled from a BOM; null for manual entries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indent_sub_items', to='bom.bomitem')),
                ('indent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='indent.indentitem')),
            ],
            options={
                'verbose_name': 'Indent Sub-Item',
                'verbose_name_plural': 'Indent Sub-Items',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['indent_item'], name='indent_inde_indent__42f04a_idx')],
            },
        ),
    ]
