# Generated by Django 5.2.7 on 2026-01-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='indent_number',
            field=models.CharField(blank=True, editable=False, help_text='System generated indent number', max_length=50, unique=True),
        ),
    ]
