# Generated by Django 5.2.7 on 2026-01-31 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_processes', to='master.processstatusmaster')),
                ('department_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_processes', to='master.departmentprocessmaster')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_po_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Process',
                'verbose_name_plural': 'PO Processes',
                'ordering': ['department_process__department', 'department_process__name'],
            },
        ),
        migrations.CreateModel(
            name='POProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_process_history_changes', to=settings.AUTH_USER_MODEL)),
                ('po_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='po.poprocess')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_process_history', to='master.processstatusmaster')),
            ],
            options={
                'verbose_name': 'PO Process History',
                'verbose_name_plural': 'PO Process Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('po_date', models.DateField()),
                ('oa_number', models.CharField(help_text='Order Acceptance Number (Unique & Mandatory)', max_length=100, unique=True, verbose_name='OA Number')),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('po_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master.companymaster', verbose_name='Supplier / Customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='poprocess',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='po.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Code')),
                ('material_description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=3, help_text='Numeric quantity (for calculations)', max_digits=12, null=True)),
                ('uom', models.CharField(default='SET', help_text='Unit of Measure', max_length=20)),
                ('material_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Material Value')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROCESS', 'In Process'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='po.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Item',
                'verbose_name_plural': 'PO Items',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='poprocess',
            unique_together={('purchase_order', 'department_process')},
        ),
    ]
