# Generated by Django 5.2.7 on 2025-10-22 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('suntech_ref_no', models.CharField(blank=True, max_length=50)),
                ('po_date', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('material_description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INPROCESS', 'In Process'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
