# Generated by Django 5.2.7 on 2026-03-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_departmentprocessmaster_excludes_from_completion_and_more'),
        ('po', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POProcessItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_item_statuses', to='po.purchaseorderitem')),
                ('po_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_statuses', to='po.poprocess')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_item_statuses', to='master.processstatusmaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_process_item_status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Process Item Status',
                'verbose_name_plural': 'PO Process Item Statuses',
                'ordering': ['po_item'],
                'unique_together': {('po_process', 'po_item')},
            },
        ),
    ]
