# Generated by Django 5.2.7 on 2025-10-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='suntech_ref_no',
        ),
    ]
