# Generated by Django 5.2.7 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_poprocessitemstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.CharField(blank=True, choices=[('Marketing', 'Marketing'), ('Design', 'Design'), ('Production', 'Production'), ('Quality', 'Quality'), ('Admin', 'Admin'), ('Logistics', 'Logistics')], max_length=50, verbose_name='Department'),
        ),
    ]
