# Generated by Django 5.2.7 on 2025-10-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('po', '0002_remove_purchaseorder_suntech_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='company_name',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='master.companymaster', verbose_name='Supplier / Customer'),
        ),
    ]
