# Generated by Django 5.2.7 on 2026-04-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_purchaseorder_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='POTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Auto-computed from selected PO items', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='po.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Target',
                'verbose_name_plural': 'PO Targets',
                'ordering': ['-year', '-month'],
                'unique_together': {('purchase_order', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='POTargetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_entries', to='po.purchaseorderitem')),
                ('po_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_items', to='po.potarget')),
            ],
            options={
                'verbose_name': 'PO Target Item',
                'verbose_name_plural': 'PO Target Items',
                'ordering': ['po_item'],
                'unique_together': {('po_target', 'po_item')},
            },
        ),
    ]
