# Generated by Django 5.2.7 on 2025-12-15 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_departmentprocessmaster'),
        ('po', '0004_alter_purchaseorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_processes', to='master.processstatusmaster')),
                ('department_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_processes', to='master.departmentprocessmaster')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_po_processes', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='po.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Process',
                'verbose_name_plural': 'PO Processes',
                'ordering': ['department_process__department', 'department_process__name'],
                'unique_together': {('purchase_order', 'department_process')},
            },
        ),
        migrations.CreateModel(
            name='POProcessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_process_history_changes', to=settings.AUTH_USER_MODEL)),
                ('po_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='po.poprocess')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_process_history', to='master.processstatusmaster')),
            ],
            options={
                'verbose_name': 'PO Process History',
                'verbose_name_plural': 'PO Process Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
