# Generated by Django 5.2.7 on 2026-01-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_poprocess_poprocesshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Code'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Material Value'),
        ),
    ]
