# Generated by Django 5.2.7 on 2026-04-29 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0005_pocomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pocomment',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PO Comment', 'verbose_name_plural': 'PO Comments'},
        ),
        migrations.AddField(
            model_name='pocomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pocomment',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pocomment',
            name='commented_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
