# Generated by Django 5.2.7 on 2026-01-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0006_purchaseorderitem_material_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
