# Generated by Django 5.2.7 on 2026-05-04 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_departmentprocessmaster_code'),
        ('po', '0007_ponote_potask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poprocessitemstatus',
            name='qty_completed',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total qty completed so far in this process step', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='POProcessItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_completed', models.DecimalField(blank=True, decimal_places=3, help_text='Qty completed in this specific update entry', max_digits=12, null=True)),
                ('remark', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_process_item_history_changes', to=settings.AUTH_USER_MODEL)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_history', to='po.purchaseorderitem')),
                ('po_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_history', to='po.poprocess')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_process_history', to='master.processstatusmaster')),
            ],
            options={
                'verbose_name': 'PO Process Item History',
                'verbose_name_plural': 'PO Process Item Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
