# Generated by Django 5.2.7 on 2026-01-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0007_purchaseorder_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Numeric quantity (for calculations)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.CharField(default='SET', help_text='Unit of Measure', max_length=20),
        ),
    ]
