# Generated by Django 5.2.7 on 2026-01-30 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0008_purchaseorderitem_quantity_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_no', models.CharField(max_length=50, unique=True)),
                ('bom_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='po.purchaseorder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bom.bom')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='po.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['bom'], name='bom_bomitem_bom_id_4d835b_idx')],
                'constraints': [models.UniqueConstraint(fields=('bom', 'po_item'), name='unique_po_item_per_bom')],
            },
        ),
    ]
