# Generated by Django 5.2.7 on 2026-03-25 05:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bomitem',
            name='unique_po_item_per_bom',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='po_item',
        ),
        migrations.AddField(
            model_name='bomitem',
            name='item',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomitem',
            name='material',
            field=models.CharField(default=datetime.datetime(2026, 3, 25, 5, 54, 51, 49101, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomitem',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
