# Generated by Django 5.2.7 on 2025-11-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_billofmaterials_created_at'),
        ('master', '0001_initial'),
        ('po', '0003_remove_purchaseorder_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['-created_at'], 'verbose_name': 'BOM Item', 'verbose_name_plural': 'BOM Items'},
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='item_name',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='bom_entries', to='master.itemmaster', verbose_name='Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='po.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(blank=True, help_text="Leave blank to use item's UOM", max_length=50, verbose_name='Unit Override'),
        ),
    ]
