# Generated by Django 5.2.7 on 2026-04-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0002_remove_bomitem_unique_po_item_per_bom_and_more'),
        ('po', '0003_purchaseorder_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomitem',
            options={'ordering': ['po_item', 'id']},
        ),
        migrations.AddField(
            model_name='bomitem',
            name='po_item',
            field=models.ForeignKey(default=1, help_text='The PO line item this BOM material belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='po.purchaseorderitem'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='bomitem',
            index=models.Index(fields=['po_item'], name='bom_bomitem_po_item_53e28c_idx'),
        ),
    ]
