# Generated by Django 5.2.7 on 2025-11-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_alter_billofmaterials_options_and_more'),
    ]

    operations = [
    ]
