# Generated by Django 5.2.7 on 2025-11-03 09:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20251103_1430'),
        ('master', '0001_initial'),
        ('po', '0003_remove_purchaseorder_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['-created_at'], 'verbose_name': 'BOM Line', 'verbose_name_plural': 'BOM Lines'},
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='master.itemmaster', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Required quantity of the item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='unit',
            field=models.CharField(editable=False, help_text='Auto-filled from ItemMaster.uom', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('po', 'item')},
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['po'], name='bom_billofm_po_id_2926c0_idx'),
        ),
        migrations.AddIndex(
            model_name='billofmaterials',
            index=models.Index(fields=['item'], name='bom_billofm_item_id_be94bd_idx'),
        ),
    ]
